### ISSUE TITLE
Slider moving faster than playback in subsequent plays

### ISSUE THREAD

**Issue by Lebari** [devivekw/TAB2XML#10]
### ID: slider1 (#10 on Github)

Tester: Greatlove B.
Title: slider moving faster than playback in subsequent plays
Version: as of March 23, 2022
Platform: Eclipse IDE, JavaSE-17, Gradle version 7.3.1 

Reproduction:
1. run the application through grade
2. paste the attached text tab into the Code Area of the window that pops up
3. click the play music button
4. click the triangle (play button) in the bottom-left corner 
5. once the music finishes playing, click the button again. Notice how the slider reaches half of its full width before the music starts playing

Expected:
On the second try, the slider will start to move only when the audio starts playing

Actual outcome:
The slider reaches three-quarters of its full width before the music starts playing (see attached screenshot)

Priority: high 
Severity: High

Attachments:

Tab music tested: 
```
CC|x---------------|--------x-------|
HH|--x-x-x-x-x-x-x-|----------------|
SD|----o-------o---|oooo------------|
HT|----------------|----oo----------|
MT|----------------|------oo--------|
BD|o-------o-------|o-------o-------|
```

<img width="564" alt="Screen Shot 2022-03-23 at 8 26 19 PM" src="https://user-images.githubusercontent.com/83144760/159822111-00777852-219a-4b9a-916d-bc074166a974.png">

**Comment by devivekw** [comment]
Fixed in [release](https://github.com/devivekw/TAB2XML/releases/tag/v0.2)
