### ISSUE TITLE
For long tabs, the music sheet goes on the next line.

### ISSUE THREAD

**Issue by sina158** [devivekw/TAB2XML#26]
ID : #[26](https://github.com/devivekw/TAB2XML/issues/26)

**Author**:
Sina Aligholizadeh

**Operating System:**
Windows 11

Version
Eclipse 2021-12 (4.22.0)
Gradle: 7.3.3
Java 17

**Description:**
After uploading the parabola.txt file which is a long music tab. the program is supposed to print the lines and notes on the next line to keep the same width of the window however it does not.

**Required Input:**
Any valid guitar or drum or bass text tabs which is long.

**Reproduction:**
Run the program
Copy and paste the text from the parabola.txt file Into the program.
Click “Preview music sheet”
extend the window to the right

**Expected Result:**
for music to be shown on the next line like the picture below:
![image](https://user-images.githubusercontent.com/46600297/159838628-fbbb7d6f-a46e-4db3-8a00-df9256aacd0b.png)

**Actual Result:**
music tabs are not printed on the next line.

**Screenshot:**

![image](https://user-images.githubusercontent.com/46600297/159838806-0c006de8-15e6-4c28-ab32-19bea31008bb.png)
![image](https://user-images.githubusercontent.com/46600297/159838889-de678ae8-bdb8-4bed-8f51-cc14dd159927.png)

**Severity: High**
most music tabs exceed one line of notes which makes the probability of reaching this issue very high

**Recommended Priority: High**
Its important to solve this issue as soon as possible to ensure program functionality for the client.

**Comment by kingsley9** [comment]
Fixed

**Comment by devivekw** [comment]
Fixed in [release](https://github.com/devivekw/TAB2XML/releases/tag/v0.2)
