### ISSUE TITLE
Sheet Music of long text-tabs cant be previewed 

### ISSUE THREAD

**Issue by Choudhry-Shaharyar** [devivekw/TAB2XML#9]
### Author:
Shaharyar Choudhry

### Operating System:
Windows 10

### Version
Eclipse 2021-12 (4.22.0)
Gradle: 7.3.3
Java 17

### Description:

After inputting [capricho.txt](https://github.com/csardana/TAB2XML/files/8337149/capricho.txt) and pressing preview sheet music, the sheet music is displayed in a new window. The problem is that the sheet music is cut off on the right side, instead of 
moving to a new line.

### Required Input:
Any long text tablature, Ex: [capricho.txt](https://github.com/csardana/TAB2XML/files/8337149/capricho.txt)

### Reproduction: 

1. Run the program
2. Copy and paste the text from the capricho.txt file into the input field.
3. Click “Preview Sheet Music”

### Expected Result:
After clicking "Preview Sheet Music I expected to see all of the sheet music for capricho.txt
### Actual Result:
Instead I only saw a portion of it since most of it was cut out.

### Screenshot of Output:
<img width="750" alt="bugreport2" src="https://user-images.githubusercontent.com/77368134/159820485-dfd1bf0d-4673-46d3-9105-33a031d2da76.PNG">

### Severity: High
It is common for artists to have long pages of music. Meaning this bug will occur on multiple occasions.

### Recommended Priority: High
Playing music is a feature that was requested by the client, therefor it should not be prioritized.

**Comment by devivekw** [comment]
Fixed in [release](https://github.com/devivekw/TAB2XML/releases/tag/v0.2)
